apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
    - name: "9229"
      port: 9229
      targetPort: 9229
  selector:
    app: api
status:
  loadBalancer: {}
