version: '3.7'

services:

  webui:
    container_name: webui
    build: ./webui
    image: 127.0.0.1:30001/ddemps14/webui
    volumes:
      - type: bind
        source: /webui
        target: /webui
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  sql-server-db:
    container_name: sql-server-db
    build: ./sql
    image: 127.0.0.1:30001/ddemps14/sql
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'password@1'
    volumes:
      - type: bind
        source: /sql/data
        target: /var/opt/mssql/

  api:
    container_name: api
    build: ./api
    image: 127.0.0.1:30001/ddemps14/api
    ports:
      - 3001:3001
      - 9229:9229
    volumes:
      - type: bind
        source: /api
        target: /api
    command:
      - node
      - "--inspect=0.0.0.0"
      - "app.js" 
volumes:
  data:
  webui:
  api: