


# indicating which version of Docker-compose we wish to use
version: "3.7"

# we will be creating these services
services:
  api:
    build: ./api
    container_name: api
    image: 127.0.0.1:30001/ddemps14/api
    ports:
      - "3001:3001"

  webui: 
    build: ./webui
    container_name: webui
    image: 127.0.0.1:30001/ddemps14/webui
    ports:
      - "8081:8081"


#   sql-server-db:
#     container_name: sql-server-db
#     build: ./sql
#     ports:
#       - 1433:1433
#     environment:
#       ACCEPT_EULA: 'Y'
#       SA_PASSWORD: 'password@1'
#     volumes:
#       - type: bind
#         source: /sql/data
#         target: /var/opt/mssql/
#     image: 127.0.0.1:30001/ddemps14/sql