apiVersion: v1
kind: Service
metadata:
  name: webui
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: webui
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 80
  selector:
    app: nginx
status:
  loadBalancer: {}

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: api
# spec:
#   ports:
#     - name: "3001"
#       port: 3001
#       targetPort: 3001
#     - name: "9229"
#       port: 9229
#       targetPort: 9229
#   selector:
#     app: api
# status:
#   loadBalancer: {}

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: sql-server-db
# spec:
#   ports:
#     - name: "1433"
#       port: 1433
#       targetPort: 1433
#   selector:
#     app: sql-server-db
# status:
#   loadBalancer: {}
