apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server-db
  template:
    metadata:
      labels:
        app: sql-server-db
    spec:
      containers:
        - name: sql-server-db
          image: 127.0.0.1:30001/ddemps14/sql
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: password@1
          resources: {}
          volumeMounts:
            - mountPath: /var/opt/mssql/
              name: data
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
status: {}
