apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
        - name: webui
          image: 127.0.0.1:30001/ddemps14/webui
          env:
            - name: CHOKIDAR_USEPOLLING
              value: "true"
          ports:
            - containerPort: 3000
          resources: {}
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /webui
              name: webui
      restartPolicy: Always
      volumes:
        - name: webui
          persistentVolumeClaim:
            claimName: webui
status: {}
